REM call cprun Browse -html -sort com_sun_beans                     
call cprun Browse -html -verbose -sort javax_accessibility
call cprun Browse -html -verbose -sort javax_crypto                     
call cprun Browse -html -verbose -sort javax_naming
call cprun Browse -html -verbose -sort javax_naming_directory           
call cprun Browse -html -verbose -sort javax_print
call cprun Browse -html -verbose -sort javax_print_attribute            
call cprun Browse -html -verbose -sort javax_print_attribute_standard
call cprun Browse -html -verbose -sort javax_print_event                
call cprun Browse -html -verbose -sort javax_security_auth
call cprun Browse -html -verbose -sort javax_security_auth_callback     
call cprun Browse -html -verbose -sort javax_security_auth_kerberos
call cprun Browse -html -verbose -sort javax_security_auth_login        
call cprun Browse -html -verbose -sort javax_security_auth_x500
call cprun Browse -html -verbose -sort javax_sound_sampled              
call cprun Browse -html -verbose -sort javax_sound_sampled_spi
call cprun Browse -html -verbose -sort javax_swing                      
call cprun Browse -html -verbose -sort javax_swing_border
call cprun Browse -html -verbose -sort javax_swing_colorchooser         
call cprun Browse -html -verbose -sort javax_swing_event
call cprun Browse -html -verbose -sort javax_swing_filechooser          
call cprun Browse -html -verbose -sort javax_swing_plaf
call cprun Browse -html -verbose -sort javax_swing_plaf_basic           
call cprun Browse -html -verbose -sort javax_swing_table
call cprun Browse -html -verbose -sort javax_swing_text                 
call cprun Browse -html -verbose -sort javax_swing_text_html
call cprun Browse -html -verbose -sort javax_swing_tree                 
call cprun Browse -html -verbose -sort javax_swing_undo
call cprun Browse -html -verbose -sort java_applet                      
call cprun Browse -html -verbose -sort java_awt
call cprun Browse -html -verbose -sort java_awt_color                   
call cprun Browse -html -verbose -sort java_awt_datatransfer
call cprun Browse -html -verbose -sort java_awt_dnd                     
call cprun Browse -html -verbose -sort java_awt_dnd_peer
call cprun Browse -html -verbose -sort java_awt_event                   
call cprun Browse -html -verbose -sort java_awt_font
call cprun Browse -html -verbose -sort java_awt_geom                    
call cprun Browse -html -verbose -sort java_awt_im
call cprun Browse -html -verbose -sort java_awt_image                   
call cprun Browse -html -verbose -sort java_awt_image_renderable
call cprun Browse -html -verbose -sort java_awt_im_spi                  
call cprun Browse -html -verbose -sort java_awt_peer
call cprun Browse -html -verbose -sort java_awt_print                   
call cprun Browse -html -verbose -sort java_beans
call cprun Browse -html -verbose -sort java_beans_beancontext           
call cprun Browse -html -verbose -sort java_io
call cprun Browse -html -verbose -sort java_lang                        
call cprun Browse -html -verbose -sort java_lang_annotation
call cprun Browse -html -verbose -sort java_lang_ref                    
call cprun Browse -html -verbose -sort java_lang_reflect
call cprun Browse -html -verbose -sort java_math                        
call cprun Browse -html -verbose -sort java_net
call cprun Browse -html -verbose -sort java_nio                         
call cprun Browse -html -verbose -sort java_nio_channels
call cprun Browse -html -verbose -sort java_nio_channels_spi            
call cprun Browse -html -verbose -sort java_nio_charset
call cprun Browse -html -verbose -sort java_nio_charset_spi             
call cprun Browse -html -verbose -sort java_security
call cprun Browse -html -verbose -sort java_security_cert               
call cprun Browse -html -verbose -sort java_security_interfaces
call cprun Browse -html -verbose -sort java_security_spec               
call cprun Browse -html -verbose -sort java_text
call cprun Browse -html -verbose -sort java_text_spi                    
call cprun Browse -html -verbose -sort java_util
call cprun Browse -html -verbose -sort java_util_concurrent             
call cprun Browse -html -verbose -sort java_util_concurrent_atomic
call cprun Browse -html -verbose -sort java_util_concurrent_locks       
call cprun Browse -html -verbose -sort java_util_jar
call cprun Browse -html -verbose -sort java_util_logging                
call cprun Browse -html -verbose -sort java_util_prefs
call cprun Browse -html -verbose -sort java_util_regex                  
call cprun Browse -html -verbose -sort java_util_spi
call cprun Browse -html -verbose -sort java_util_zip                     
call cprun Browse -html -verbose -sort org_w3c_dom
call cprun Browse -html -verbose -sort org_xml_sax                      
call cprun Browse -html -verbose -sort sun_awt
call cprun Browse -html -verbose -sort sun_awt_color                    
call cprun Browse -html -verbose -sort sun_awt_datatransfer
call cprun Browse -html -verbose -sort sun_awt_dnd                      
call cprun Browse -html -verbose -sort sun_awt_geom
call cprun Browse -html -verbose -sort sun_awt_im                       
call cprun Browse -html -verbose -sort sun_awt_image
call cprun Browse -html -verbose -sort sun_awt_shell                    
call cprun Browse -html -verbose -sort sun_awt_util
call cprun Browse -html -verbose -sort sun_awt_windows                  
call cprun Browse -html -verbose -sort sun_dc_path
call cprun Browse -html -verbose -sort sun_dc_pr                        
call cprun Browse -html -verbose -sort sun_font
call cprun Browse -html -verbose -sort sun_java2d                       
call cprun Browse -html -verbose -sort sun_java2d_loops
call cprun Browse -html -verbose -sort sun_java2d_pipe                  
call cprun Browse -html -verbose -sort sun_java2d_pipe_hw
call cprun Browse -html -verbose -sort sun_misc                         
call cprun Browse -html -verbose -sort sun_net
call cprun Browse -html -verbose -sort sun_net_idn                      
call cprun Browse -html -verbose -sort sun_net_spi_nameservice
call cprun Browse -html -verbose -sort sun_net_www                      
call cprun Browse -html -verbose -sort sun_nio_ch
call cprun Browse -html -verbose -sort sun_nio_cs                       
call cprun Browse -html -verbose -sort sun_nio_cs_ext
call cprun Browse -html -verbose -sort sun_print                        
call cprun Browse -html -verbose -sort sun_reflect
call cprun Browse -html -verbose -sort sun_reflect_annotation           
call cprun Browse -html -verbose -sort sun_reflect_generics_factory
call cprun Browse -html -verbose -sort sun_reflect_generics_repository  
call cprun Browse -html -verbose -sort sun_reflect_generics_scope
call cprun Browse -html -verbose -sort sun_reflect_generics_tree        
call cprun Browse -html -verbose -sort sun_reflect_generics_visitor
call cprun Browse -html -verbose -sort sun_security_jca                 
call cprun Browse -html -verbose -sort sun_security_pkcs
call cprun Browse -html -verbose -sort sun_security_provider_certpath   
call cprun Browse -html -verbose -sort sun_security_util
call cprun Browse -html -verbose -sort sun_security_validator           
call cprun Browse -html -verbose -sort sun_security_x509
call cprun Browse -html -verbose -sort sun_swing                        
call cprun Browse -html -verbose -sort sun_swing_text_html
call cprun Browse -html -verbose -sort sun_text                         
call cprun Browse -html -verbose -sort sun_text_normalizer
call cprun Browse -html -verbose -sort sun_util                         
call cprun Browse -html -verbose -sort sun_util_calendar
call cprun Browse -html -verbose -sort sun_util_resources                
